### ISSUE TITLE
Is it possible to persist a connection key for re-use?

### ISSUE THREAD

**Issue by draeder** [mafintosh/hyperbeam#14]
I have a server that I intend should stay up 100% of the time, but sometimes things happen. That server will be creating hyperbeam sessions for clients. Let's say the server needs to be restarted, or the client loses its connection. 

Is there a way to re-use the initial connection key?

**Comment by mafintosh** [comment]
At that point I’d just make a server instance using the hyperswarm/dht module, have you looked at that?

**Comment by draeder** [comment]
I have, and it's what I'm working on now. Basically using a hyperswarm 'topic' for discovery, then exchange keys, then hyperbeam.... The documentation seems to need a little more work. It's not clear what events are emitted between the various libraries, and they all seem to be different. It would be nice if they all settled on the same event for the same type of thing: 'close' means disconnect, etc.

**Comment by draeder** [comment]
The switch to Base32 made this harder to use, but I understand why...
